words = [
    "cryptocurrency",
    "deep learning",
    "adaptive",
    "agile",
    "ai",
    "ajax",
    "algorithm",
    "android",
    "analytics",
    "api",
    "artificial intelligence",
    "augmented",
    "authentication",
    "big data",
    "biometric",
    "bitcoin",
    "blockchain",
    "bot",
    "botnet",
    "bootstrap",
    "cloud",
    "cloud-based",
    "cross-platform",
    "cyber",
    "cyber-security",
    "cybersecurity",
    "data mining",
    "dark web",
    "deep web",
    "devops",
    "encryption",
    "encrypted",
    "end-to-end",
    "framework",
    "functional",
    "gdpr",
    "graphics processing",
    "hackathon",
    "hacker",
    "hacking",
    "internet of things",
    "ios",
    "iot",
    "linux",
    "machine learning",
    "mobile",
    "multi-threading",
    "multi-core",
    "neural network",
    "network",
    "networking",
    "predictive",
    "polymorphism",
    "quantum",
    "real time",
    "real-time",
    "referential transparency",
    "responsive",
    "rest",
    "scalability",
    "science",
    "scrum",
    "security",
    "serverless",
    "skeuomorphic",
    "software",
    "tape drive",
    "threat management",
    "tor",
    "tuples",
    "turing complete",
    "ubuntu",
    "unit test",
    "unix",
    "virtual reality",
    "vim",
    "vr",
    "waterfall",
    "web app"
]
